#!/usr/bin/python3

import json


SinglyLinkedList = __import__('100-singly_linked_list').SinglyLinkedList
filename = "my_list.json"

sll = SinglyLinkedList()
for count in range(0, 10):
    sll.sorted_insert(count)

print("Elements of the linked lists:")
print(sll)
print()

# Create file if file does not exist

try:
    myFile = open(filename, mode="r", encoding="utf-8")
    myFile.close()
except FileNotFoundError:
    with open(filename, mode="w", encoding="utf-8") as myFile:
        json.dumps(str(), myFile)

# Storing to file

with open(filename, mode="w", encoding="utf-8") as myFile:
    json.dumps(str(sll), myFile, sort_keys=True, indent=4)
