#!/usr/bin/env bash
# Automate - installation and configuration of an Ubuntu macine to for nginx server
# It has a custome error page
# Ensure to use 'sudo' previleges if you are not a super user

default_index='/var/www/html/index.nginx-debian.html'
SITE='/var/www/html'
server_config='/etc/nginx/sites-enabled/default'
server_config_temp='./server_config_4'
error_page="$SITE/404.html"

# Install nginx server
apt-get -y install nginx

# Set ufw status - Adjust the Firewal
ufw allow 'Nginx HTTP'

# Configure user to own site
chown -R "$USER":"$USER" "$SITE"

# Create landing page
echo 'Hello World!' > "$default_index"

# Create error page
echo "Ceci n'est pas une page" > "$error_page"

# Configure server
cp "$server_config_temp" "$server_config"

# Restart service
service nginx restart
